[package]
name = "image-as-text"
version = "0.0.0"
authors = ["Patrick Winters <19wintersp@gmail.com>"]
edition = "2018"
description = "CLI to turn an image into Unicode text"

[dependencies]
braille = "1.0.3"
image = "0.23.14"
clap = "2.33.3"
